set_date_time:
  target:
    entity:
      domain: alarm_control_panel
  fields:
    datetime:
      name: Date & Time to set
      description: The date/time to set. The time zone of the Home Assistant instance is assumed. Defaults to current date/time if unset.
      required: false
      example: "2022/11/01 22:15"
      selector:
        datetime: